<?xml version="1.0"?>
<package format="3">
  <name>obstacle_avoid</name>
  <version>1.0.0</version>
  <description>Exemple : évitement d'obstacles simple (télémètre avant -> consigne de vitesse OFFBOARD)</description>
  <maintainer email="vous@exemple.com">drone-sim</maintainer>
  <license>MIT</license>


  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>mavros_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
